/*
*  Copyright 2024 MASES s.r.l.
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*  http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
*
*  Refer to LICENSE for more information.
*/

/*
*  This file is generated by MASES.JNetReflector (ver. 2.5.9.0)
*  using android.jar as reference
*/

using MASES.JCOBridge.C2JBridge;

namespace Android.Health.Connect
{
    #region LocalTimeRangeFilter declaration
    /// <summary>
    /// <see href="https://developer.android.com/reference/android/health/connect/LocalTimeRangeFilter.html"/>
    /// </summary>
    public partial class LocalTimeRangeFilter : Android.Health.Connect.TimeRangeFilter
    {
        const string _bridgeClassName = "android.health.connect.LocalTimeRangeFilter";
        /// <summary>
        /// Default constructor: even if the corresponding Java class does not have one, it is mandatory for JCOBridge
        /// </summary>
        public LocalTimeRangeFilter() { }
        /// <summary>
        /// Generic constructor: it is useful for JCOBridge when there is a derived class which needs to pass arguments to the highest JVMBridgeBase class
        /// </summary>
        public LocalTimeRangeFilter(params object[] args) : base(args) { }
    
        private static readonly MASES.JCOBridge.C2JBridge.JVMInterop.IJavaType _LocalBridgeClazz = JVMBridgeBase.ClazzOf(_bridgeClassName);
        private static MASES.JCOBridge.C2JBridge.JVMInterop.IJavaType LocalBridgeClazz => _LocalBridgeClazz ?? throw new global::System.InvalidOperationException($"Class {_bridgeClassName} was not found.");
    
        /// <summary>
        /// <see href="https://www.jcobridge.com/api-clr/html/P_MASES_JCOBridge_C2JBridge_JVMBridgeBase_BridgeClassName.htm"/>
        /// </summary>
        public override string BridgeClassName => _bridgeClassName;
        /// <summary>
        /// <see href="https://www.jcobridge.com/api-clr/html/P_MASES_JCOBridge_C2JBridge_JVMBridgeBase_IsBridgeAbstract.htm"/>
        /// </summary>
        public override bool IsBridgeAbstract => false;
        /// <summary>
        /// <see href="https://www.jcobridge.com/api-clr/html/P_MASES_JCOBridge_C2JBridge_JVMBridgeBase_IsBridgeCloseable.htm"/>
        /// </summary>
        public override bool IsBridgeCloseable => false;
        /// <summary>
        /// <see href="https://www.jcobridge.com/api-clr/html/P_MASES_JCOBridge_C2JBridge_JVMBridgeBase_IsBridgeInterface.htm"/>
        /// </summary>
        public override bool IsBridgeInterface => false;
        /// <summary>
        /// <see href="https://www.jcobridge.com/api-clr/html/P_MASES_JCOBridge_C2JBridge_JVMBridgeBase_IsBridgeStatic.htm"/>
        /// </summary>
        public override bool IsBridgeStatic => false;
    
        // TODO: complete the class
        #region Builder declaration
        /// <summary>
        /// <see href="https://developer.android.com/reference/android/health/connect/LocalTimeRangeFilter.Builder.html"/>
        /// </summary>
        public partial class Builder : MASES.JCOBridge.C2JBridge.JVMBridgeBase<Builder>
        {
            const string _bridgeClassName = "android.health.connect.LocalTimeRangeFilter$Builder";
            /// <summary>
            /// Default constructor: even if the corresponding Java class does not have one, it is mandatory for JCOBridge
            /// </summary>
            public Builder() { }
            /// <summary>
            /// Generic constructor: it is useful for JCOBridge when there is a derived class which needs to pass arguments to the highest JVMBridgeBase class
            /// </summary>
            public Builder(params object[] args) : base(args) { }
        
            private static readonly MASES.JCOBridge.C2JBridge.JVMInterop.IJavaType _LocalBridgeClazz = JVMBridgeBase.ClazzOf(_bridgeClassName);
            private static MASES.JCOBridge.C2JBridge.JVMInterop.IJavaType LocalBridgeClazz => _LocalBridgeClazz ?? throw new global::System.InvalidOperationException($"Class {_bridgeClassName} was not found.");
        
            /// <summary>
            /// <see href="https://www.jcobridge.com/api-clr/html/P_MASES_JCOBridge_C2JBridge_JVMBridgeBase_BridgeClassName.htm"/>
            /// </summary>
            public override string BridgeClassName => _bridgeClassName;
            /// <summary>
            /// <see href="https://www.jcobridge.com/api-clr/html/P_MASES_JCOBridge_C2JBridge_JVMBridgeBase_IsBridgeAbstract.htm"/>
            /// </summary>
            public override bool IsBridgeAbstract => false;
            /// <summary>
            /// <see href="https://www.jcobridge.com/api-clr/html/P_MASES_JCOBridge_C2JBridge_JVMBridgeBase_IsBridgeCloseable.htm"/>
            /// </summary>
            public override bool IsBridgeCloseable => false;
            /// <summary>
            /// <see href="https://www.jcobridge.com/api-clr/html/P_MASES_JCOBridge_C2JBridge_JVMBridgeBase_IsBridgeInterface.htm"/>
            /// </summary>
            public override bool IsBridgeInterface => false;
            /// <summary>
            /// <see href="https://www.jcobridge.com/api-clr/html/P_MASES_JCOBridge_C2JBridge_JVMBridgeBase_IsBridgeStatic.htm"/>
            /// </summary>
            public override bool IsBridgeStatic => true;
        
            // TODO: complete the class
        
        }
        #endregion

    
    }
    #endregion

    #region LocalTimeRangeFilter implementation
    public partial class LocalTimeRangeFilter
    {
        #region Constructors
    
        #endregion
    
        #region Class/Interface conversion operators
    
        #endregion
    
        #region Fields
    
        #endregion
    
        #region Static methods
    
        #endregion
    
        #region Instance methods
        /// <summary>
        /// <see href="https://developer.android.com/reference/android/health/connect/LocalTimeRangeFilter.html#isBounded()"/>
        /// </summary>
        /// <returns><see cref="bool"/></returns>
        public bool IsBounded()
        {
            return IExecuteWithSignature<bool>("isBounded", "()Z");
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/android/health/connect/LocalTimeRangeFilter.html#getEndTime()"/>
        /// </summary>
        /// <returns><see cref="Java.Time.LocalDateTime"/></returns>
        public Java.Time.LocalDateTime GetEndTime()
        {
            return IExecuteWithSignature<Java.Time.LocalDateTime>("getEndTime", "()Ljava/time/LocalDateTime;");
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/android/health/connect/LocalTimeRangeFilter.html#getStartTime()"/>
        /// </summary>
        /// <returns><see cref="Java.Time.LocalDateTime"/></returns>
        public Java.Time.LocalDateTime GetStartTime()
        {
            return IExecuteWithSignature<Java.Time.LocalDateTime>("getStartTime", "()Ljava/time/LocalDateTime;");
        }
    
        #endregion
    
        #region Nested classes
        #region Builder implementation
        public partial class Builder
        {
            #region Constructors
        
            #endregion
        
            #region Class/Interface conversion operators
        
            #endregion
        
            #region Fields
        
            #endregion
        
            #region Static methods
        
            #endregion
        
            #region Instance methods
            /// <summary>
            /// <see href="https://developer.android.com/reference/android/health/connect/LocalTimeRangeFilter.Builder.html#build()"/>
            /// </summary>
            /// <returns><see cref="Android.Health.Connect.LocalTimeRangeFilter"/></returns>
            public Android.Health.Connect.LocalTimeRangeFilter Build()
            {
                return IExecuteWithSignature<Android.Health.Connect.LocalTimeRangeFilter>("build", "()Landroid/health/connect/LocalTimeRangeFilter;");
            }
            /// <summary>
            /// <see href="https://developer.android.com/reference/android/health/connect/LocalTimeRangeFilter.Builder.html#setEndTime(java.time.LocalDateTime)"/>
            /// </summary>
            /// <param name="arg0"><see cref="Java.Time.LocalDateTime"/></param>
            /// <returns><see cref="Android.Health.Connect.LocalTimeRangeFilter.Builder"/></returns>
            public Android.Health.Connect.LocalTimeRangeFilter.Builder SetEndTime(Java.Time.LocalDateTime arg0)
            {
                return IExecuteWithSignature<Android.Health.Connect.LocalTimeRangeFilter.Builder>("setEndTime", "(Ljava/time/LocalDateTime;)Landroid/health/connect/LocalTimeRangeFilter$Builder;", arg0);
            }
            /// <summary>
            /// <see href="https://developer.android.com/reference/android/health/connect/LocalTimeRangeFilter.Builder.html#setStartTime(java.time.LocalDateTime)"/>
            /// </summary>
            /// <param name="arg0"><see cref="Java.Time.LocalDateTime"/></param>
            /// <returns><see cref="Android.Health.Connect.LocalTimeRangeFilter.Builder"/></returns>
            public Android.Health.Connect.LocalTimeRangeFilter.Builder SetStartTime(Java.Time.LocalDateTime arg0)
            {
                return IExecuteWithSignature<Android.Health.Connect.LocalTimeRangeFilter.Builder>("setStartTime", "(Ljava/time/LocalDateTime;)Landroid/health/connect/LocalTimeRangeFilter$Builder;", arg0);
            }
        
            #endregion
        
            #region Nested classes
        
            #endregion
        
            // TODO: complete the class
        }
        #endregion

    
        #endregion
    
        // TODO: complete the class
    }
    #endregion
}